// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjjmqckytldclyzasbqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqam1xY2t5dGxkY2x5emFzYnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODk4MDcsImV4cCI6MjA2ODE2NTgwN30.0qMw5pK086QMSL5xDVA6MtVsxDUvGXfkuTWYOw88DWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});